/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flex_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(228916e93dac90182617902aa5eabfc9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pager/flex_decode.h>
// pydoc.h is automatically generated in the build directory
#include <flex_decode_pydoc.h>

void bind_flex_decode(py::module& m)
{

    using flex_decode    = ::gr::pager::flex_decode;


    py::class_<flex_decode, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<flex_decode>>(m, "flex_decode", D(flex_decode))

        .def(py::init(&flex_decode::make),
           py::arg("freq"),
           D(flex_decode,make)
        )
        




        
        .def("set_freq",&flex_decode::set_freq,       
            py::arg("freq"),
            D(flex_decode,set_freq)
        )


        
        .def("get_freq",&flex_decode::get_freq,       
            D(flex_decode,get_freq)
        )

        ;




}








