/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flex_deinterleave.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d10e4abf64f7368dcac20d5ef1ca9f8b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pager/flex_deinterleave.h>
// pydoc.h is automatically generated in the build directory
#include <flex_deinterleave_pydoc.h>

void bind_flex_deinterleave(py::module& m)
{

    using flex_deinterleave    = ::gr::pager::flex_deinterleave;


    py::class_<flex_deinterleave, gr::sync_decimator,
        std::shared_ptr<flex_deinterleave>>(m, "flex_deinterleave", D(flex_deinterleave))

        .def(py::init(&flex_deinterleave::make),
           D(flex_deinterleave,make)
        )
        



        ;




}








