/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(flex_parse.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(36aedc2de7b8e11a34f1e5a063b01208)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pager/flex_parse.h>
// pydoc.h is automatically generated in the build directory
#include <flex_parse_pydoc.h>

void bind_flex_parse(py::module& m)
{

    using flex_parse    = ::gr::pager::flex_parse;


    py::class_<flex_parse, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<flex_parse>>(m, "flex_parse", D(flex_parse))

        .def(py::init(&flex_parse::make),
           py::arg("queue"),
           py::arg("freq"),
           D(flex_parse,make)
        )
        



        ;




}








